name: CI

on:
  push:
    branches:
      - dev
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          KAKAO_REST_API_KEY: ${{ secrets.KAKAO_REST_API_KEY }}
          KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}
        run: npm run build

      - name: Create build env file
        run: |
          cat <<EOF > .env.production.local
          POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          KAKAO_REST_API_KEY=${{ secrets.KAKAO_REST_API_KEY }}
          KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}
          EOF

      - name: Build Docker image
        run: |
          docker build \
            --secret id=env,src=.env.production.local \
            -t ounwan:ci \
            .

      # [AWS] 자격 증명 발급
      - name: Configure AWS credentials
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::789748176137:role/OunwanGitHubActionsRole
          aws-region: ap-northeast-2

      # [AWS] ECR 로그인
      - name: Login to Amazon ECR
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/amazon-ecr-login@v2

      # [AWS] ECR Push
      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag ounwan:ci 789748176137.dkr.ecr.ap-northeast-2.amazonaws.com/ounwan-app:${{ github.sha }}
          docker tag ounwan:ci 789748176137.dkr.ecr.ap-northeast-2.amazonaws.com/ounwan-app:latest

          docker push 789748176137.dkr.ecr.ap-northeast-2.amazonaws.com/ounwan-app:${{ github.sha }}
          docker push 789748176137.dkr.ecr.ap-northeast-2.amazonaws.com/ounwan-app:latest
